name: ci

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: ci
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checks if project has no errors
        run: cargo check
